# Generated by Django 5.0.3 on 2024-03-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.TextField(verbose_name=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("info", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
