# Generated by Django 5.0.3 on 2024-03-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductModel",
            new_name="Product",
        ),
    ]
