# Generated by Django 5.0.3 on 2024-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_rename_productmodel_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="info",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.TextField(max_length=250),
        ),
    ]
