# Generated by Django 5.0.3 on 2024-03-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_alter_product_info_alter_product_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=20),
        ),
    ]
